ALTER TABLE tickets
  ADD COLUMN IF NOT EXISTS attendant_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS attendant_name TEXT,
  ADD COLUMN IF NOT EXISTS resolution_notes TEXT;