# .github/workflows/scheduler.yml

name: Disparador de Notificações de Eventos

on:
  schedule:
    # Corre todos os dias às 11:30 UTC, que corresponde às 08:30 no horário de Brasília (UTC-3)
    - cron: "04 17 * * *"
  workflow_dispatch: # Permite acionar manualmente pela interface do GitHub

jobs:
  trigger_email_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar a rota de notificação de eventos
        run: |
          curl -X POST ${{ secrets.RENDER_CRON_TRIGGER_URL }} \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}" \
          -H "Content-Length: 0"
